name: multicampus_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - tqdm
  - pandas
  - pyarrow
  - matplotlib
  - seaborn
  - pip
  - pip:
      - gensim
      - konlpy
      - selenium
      - undetected-chromedriver
      - beautifulsoup4
      - wordcloud
# 설치 법
# conda env update -f environment.yml
